### ISSUE TITLE
漫画画面の仕事分担

### ISSUE THREAD

**Issue by mehm8128** [hackathon-22-digicon-team4/comiQ-UI#5]
- [x] 漫画画像(1枚目と最後のページは特殊)
  - 1枚目と最後のページ以外完
- [x] スタンプ一覧(画面下部)
  - s9くん
- [x] スタンプ一覧(画面下部で足りないときのモーダル)
  - 多分mehm8128
  - スタンプたくさん準備するわけじゃないし別にいらないかも
- [x] 表示・非表示切り替え
  - s9くん
- [x] スタンプ選択状態で漫画画像クリック時に置かれるスタンプ・スタンプ削除ボタン
  - mehm8128

**Comment by mehm8128** [comment]
スタンプ一覧について
- スタンプをクリックしたとき、"selected"っていうemitでクリックされたスタンプをMangaViewに対して出すようにしてほしい(emitは僕がカルーセルのところで使ってるので参考にしてみてください)
- スタンプは今はimgタグだけだけど、クリックするのでbuttonタグで挟んでほしい
- スタンプ一覧の一番右側に、クリックしたらモーダルを出すボタンを置いてほしい。モーダル自体は僕が実装するので、クリックしたら適当な関数を発火するようにしておいてほしい(モーダルは表示しきれない分を置くので、画面下部に置くスタンプは上限を決めておいてほしい)(スタンプたくさん用意するわけじゃないし別にいらないかも)
- スタンプはmockを使うのではなく、APIを叩いたら取得できるようにしてみてほしい

**Comment by mehm8128** [comment]
表示・非表示切替について
- 自分ボタンと他人ボタンがあって、2^2=4通りの状態がある
- それぞれのボタンがクリックされた状態ではスタンプを表示するようにする
- 表示・非表示コンポーネントから表示するか非表示するかについてのbooleanをemitでMangaViewに対して出してほしい(`isMyStampShow`,`isOtherStampShow`みたいな感じの名前で)
- (他人のだけ取得するAPIあったか分からないから要確認な気がしてきた)

**Comment by mehm8128** [comment]
(これは自分用メモなので気にしなくて大丈夫です)
- スタンプ一覧からemitされたら選択しているスタンプを変更し、MangaComponemtに流す
- 表示/非表示ボタンからemitされたらその漫画に押されているスタンプ情報をfetchしてMngaComponentに流す
- 漫画画像クリック時にマウスカーソルの座標情報を取得してその位置にスタンプを置く&POSTする
  - スタンプをホバーしたら×ボタンが表示されて、クリックするとスタンプを消してDELETEする
  - クライアントの状態を変更して、再fetchはしない
- デモ版では問題ないけど、スタンプが大量になったときに重くなるのでできればページをクエリパラメータで指定してページごとにスタンプを取れるようにしたい 
  - その場合、1つ前の見開きページに入ったタイミングで裏でfetchしておけば次のページに入るときにすぐ見れるはず

**Comment by s9-sukyu** [comment]
求められた部分を実装したつもりです

**Comment by s9-sukyu** [comment]
漫画画像の最初と最後のページやりましょうか？

**Comment by mehm8128** [comment]
お願いします🙏
スタンプの統計情報はクライアントで計算するよりサーバーから返してもらった方がよさそうなのでお願いした方がいいかも(最悪なくていいけど)
